---
- name: install core packages for container machines
  hosts: "{{ hosts }}"
  become: yes
  tasks:
  - name: install packages
    apt:
      name:
        - htop
        - curl
        - unzip
        - mlocate
        - git
        - qemu-guest-agent
      update_cache: yes