- name: Install all updates and reboot as many times as needed
  hosts: all
  tasks:
    - name: Run Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        state: installed