---
- name: Update Windows Servers
  hosts: all
  tasks:
    - name: Install all critical and security updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
      register: update_result

    - name: Display update results
      debug:
        var: update_result
