---
- name: Fetch TightVNC latest 64-bit MSI package using curl
  hosts: localhost
  tasks:
    - name: Fetch the download page content with curl
      ansible.builtin.shell: |
        curl -s https://www.tightvnc.com/download.php | grep -oP 'https://.*tightvnc.*64.*\.msi(?=")'
      register: curl_output

    - name: Set the download URL from curl output
      set_fact:
        download_url: "{{ curl_output.stdout }}"

    - name: Debug the extracted download URL
      debug:
        var: download_url

    - name: Download TightVNC MSI package
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: /tmp/tightvnc_latest_x64.msi
