---
- name: Fetch TightVNC latest 64-bit MSI package
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch the download page content with curl
      ansible.builtin.shell: |
        curl -s https://www.tightvnc.com/download.php | grep -oP 'https://.*tightvnc.*64.*\.msi(?=")'
      register: curl_output

    - name: Set the download URL from curl output
      set_fact:
        download_url: "{{ curl_output.stdout }}"

    - name: Debug the extracted download URL
      debug:
        var: download_url

- name: Install TightVNC on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure the TightVNC MSI package is downloaded
      win_get_url:
        url: "{{ hostvars['localhost'].download_url }}"
        dest: "C:\\Users\\{{ ansible_user }}\\AppData\\Local\\Temp\\tightvnc_latest_x64.msi"

    - name: Ensure C:\ansi_log directory exists
      ansible.windows.win_file:
        path: C:\ansi_log
        state: directory

    - name: Install TightVNC MSI package
      ansible.windows.win_package:
        path: "C:\\Users\\{{ ansible_user }}\\AppData\\Local\\Temp\\tightvnc_latest_x64.msi"
        state: present
        arguments: '/quiet /norestart ADDLOCAL="Server" SERVER_REGISTER_AS_SERVICE="1" SERVER_ADD_FIREWALL_EXCEPTION="1" SERVER_ALLOW_SAS="1" SET_USEVNCAUTHENTICATION="1" VALUE_OF_USEVNCAUTHENTICATION="1" SET_PASSWORD="1" VALUE_OF_PASSWORD="accesspass" SET_USECONTROLAUTHENTICATION="1" VALUE_OF_USECONTROLAUTHENTICATION="1" SET_CONTROLPASSWORD="1" VALUE_OF_CONTROLPASSWORD="adminpass" SET_IPACCESSCONTROL="1" VALUE_OF_IPACCESSCONTROL="0.0.0.0-255.255.255.255:2" SET_REMOVEWALLPAPER="1" VALUE_OF_REMOVEWALLPAPER="0"'
        log_path: C:\ansi_log\tightvnc-{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}.log
      register: install_result

    - name: Debugging install_result
      debug:
        var: install_result

    - name: Cleanup TightVNC MSI package from Windows machine
      win_file:
        path: "C:\\Users\\{{ ansible_user }}\\AppData\\Local\\Temp\\tightvnc_latest_x64.msi"
        state: absent

- name: Cleanup Temporary Files on Control Node
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Cleanup TightVNC MSI package from Linux control node
      ansible.builtin.file:
        path: /tmp/tightvnc_latest_x64.msi
        state: absent
