---
- name: Fetch TightVNC latest 64-bit MSI package
  hosts: localhost
  tasks:
    - name: Get the download page content
      ansible.builtin.uri:
        url: https://www.tightvnc.com/download.php
        return_content: yes
      register: page_content

    - name: Extract the 64-bit MSI download URL
      set_fact:
        download_url: "{{ page_content.content | regex_search('https://.*tightvnc.*64.*\\.msi(?=\")', '\\g<0>') }}"

    - name: Debug the extracted download URL
      debug:
        var: download_url

    - name: Download TightVNC MSI package
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: /tmp/tightvnc_latest_x64.msi
