#---
#- name: Install vnc program
#  hosts: all
#  tasks:
#    - name: Downloading and installing vnc
#      ansible.windows.win_package:
#        path: https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi
#        arguments:
#        - /quiet
#        - /norestart
#        - SET_USEVNCAUTHENTICATION=1
#        - VALUE_OF_USEVNCAUTHENTICATION=1
#        - SET_PASSWORD=1
#        - VALUE_OF_PASSWORD=demo1234
        #- SET_IPACCESSCONTROL="0.0.0.0-:2"
#        log_path: C:\tmp\vnc-{{lookup('pipe', 'date +%Y%m%dT%H%M%S')}}.log
#      register: vnc_install_result
#
---
- name: Install TightVNC on Windows 10
  hosts: windows
  tasks:
    - name: Download TightVNC latest 64-bit MSI package
      ansible.builtin.uri:
        url: https://www.tightvnc.com/download.php
      register: page_content

    - name: Extract the 64-bit MSI download URL
      set_fact:
        download_url: "{{ page_content.content | regex_search('https://.*tightvnc.*64.*\\.msi(?=\")') }}"

    - name: Download the latest 64-bit TightVNC MSI package to Windows machine
      win_get_url:
        url: "{{ download_url }}"
        dest: C:\temp\tightvnc_latest_x64.msi

    - name: Install TightVNC MSI package
      win_package:
        path: C:\temp\tightvnc_latest_x64.msi
        state: present
        arguments:
        - /quiet
        - /norestart
        - SET_USEVNCAUTHENTICATION=1
        - VALUE_OF_USEVNCAUTHENTICATION=1
        - SET_PASSWORD=1
        - VALUE_OF_PASSWORD=demo1234
        - SET_IPACCESSCONTROL="0.0.0.0-:2"
