---
- name: Install urbackup application
  hosts: all
  tasks:
    - name: Install urackup
      ansible.windows.win_package:
        path: https://hndl.urbackup.org/Client/latest/UrBackup%20Client%202.5.25%28x64%29.msi
        arguments:
        - /quiet