---
- name: Fetch TightVNC latest 64-bit MSI package (Linux/Ansible controller)
  hosts: localhost  # Run this only on the Ansible controller or a Linux machine
  tasks:
    - name: Get the download page content
      ansible.builtin.uri:
        url: https://www.tightvnc.com/download.php
      register: page_content

    - name: Extract the 64-bit MSI download URL
      set_fact:
        download_url: "{{ page_content.content | regex_search('https://.*tightvnc.*64.*\\.msi(?=\")') }}"
      delegate_to: localhost  # Ensures the fact is set on the controller, not on Windows hosts

- name: Install TightVNC on Windows 10
  hosts: all
  tasks:
    - name: Download TightVNC MSI package to Windows machine
      win_get_url:
        url: "{{ download_url }}"
        dest: C:\temp\tightvnc_latest_x64.msi

    - name: Install TightVNC MSI package
      win_package:
        path: C:\temp\tightvnc_latest_x64.msi
        state: present
        arguments:
        - /quiet
        - /norestart
        - SET_USEVNCAUTHENTICATION=1
        - VALUE_OF_USEVNCAUTHENTICATION=1
        - SET_PASSWORD=1
        - VALUE_OF_PASSWORD=demo1234
        - SET_IPACCESSCONTROL="0.0.0.0-:2"
