---
- name: Update DrukiGofin program
  hosts: all
  tasks:
    - name: Ensure C:\ansi_log directory exists
      ansible.windows.win_file:
        path: C:\ansi_log
        state: directory
        
    - name: Downloading and installing DrukiGofin
      ansible.windows.win_package:
        path: https://druki.gofin.pl/download-msi
        arguments:
        - /update
        - /norestart
        - /passive
        log_path: C:\tmp\DrukiGofin-{{lookup('pipe', 'date +%Y%m%dT%H%M%S')}}.log
      register: install_result
    
    - name: Debugging install_result
      debug:
        var: install_result
