---
- name: Set timezone to Asia/Tokyo
  hosts: all
  #become: yes  # To run tasks with sudo privileges

  tasks:
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Asia/Tokyo
